services:
  - type: web
    name: almadom-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TOKEN
        value: ${TOKEN}
      - key: WEBHOOK_URL
        value: ${WEBHOOK_URL}